name: Publish to Pypi
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # regex to match semantic versioning tags

jobs:
  deploy:
    name: Deploy python package
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying .."