name: Publish to Pypi
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # regex to match semantic versioning tags

jobs:
  tests:
    uses: ./.github/workflows/main.yml
  deploy:
    name: Deploy python package
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying .."